indexer_host: "https://algoindexer.algoexplorerapi.io"
indexer_api_token: ""
port: "8081"
metrics_port: "9361"
start_round: 0
fetcher_rps: 5
log_level: info
redis_host: "redis:6379"
redis_password: "password"
publisher_timeout: "3s"
new_block_channel: "algorand-notification-new-block"
